services:
  # Backend API Service
  - type: web
    name: youtube-clone-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        fromDatabase:
          name: youtube-clone-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        fromService:
          type: web
          name: youtube-clone-frontend
          property: host
      - key: UPLOAD_PATH
        value: ./public/uploads
      - key: MAX_FILE_SIZE
        value: 100000000

  # Frontend Static Site
  - type: web
    name: youtube-clone-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: youtube-clone-backend
          property: host
        value: /api
      - key: REACT_APP_NAME
        value: YouTube Clone
      - key: REACT_APP_VERSION
        value: 1.0.0

databases:
  - name: youtube-clone-db
    databaseName: youtube_clone
    user: youtube_user
    region: oregon
    plan: free
